### ISSUE TITLE
JSON Deserialization of 2..n objects without an ID gets weird results

### ISSUE THREAD

**Issue by jmlutgemeier** [cradlepoint/JsonAPIary#10]
Hey, me again. I discovered some behavior I think it is worth to discuss. 

We have the following use case:

think of an customer API endpoint to create customers. E.g.
POST api/customers

where a list of customers can be given in as body, e.g.:
{
  "data": [
    {
      "type": "customer",
      "attributes": {
        "name": "Best Customer",
        "age": 40,
        "someother": "value"
      }
    },
    {
      "type": "customer",
      "attributes": {
        "name": "Best Customer2",
        "age": 80,
        "someother": "cool!"
      }
    }
  ]
}

Note: There is no ID in one of these objects because they need to be created.

Now the behavior is, that after JsonApiAiry with Jackson deserializes the JSON shown above to an Java List with 2 identical objects. The ID of both is, as expected, null, but the attributes are equal,  and the attributes section of the second new customer gets ignored/forgotten.

Why is that so?

**Comment by loganleyva** [comment]
This was a really great find! Due to JsonAPI being so... "complicated", the deserialization logic has to maintain a map of all of the unique objects within the JSON blob. In order to de-duplicate any found objects (since the same object could technically appear multiple times within the same JSON) the key to that map is a combination of the ID and Type for each object.

In this case, since multiple object have an ID of null (and they are all of the same type) the deserializer assumed they were both the same object and ran only once for both. I have an MR up now that will address this issue by essentially assigning an random value as the ID for each different object with a null ID found in the JSON. It should be integrated shortly!.

**Comment by loganleyva** [comment]
This issue is now fixed on main. Please feel free to let me know if you run into any other issues around this.

**Comment by jmlutgemeier** [comment]
Thanks!!
